# Archwright default launcher.
font=JetBrainsMono Nerd Font:size=12
lines=12
width=40
horizontal-pad=16
vertical-pad=12

[colors]
background=1d2021ee
text=ebdbb2ff
selection=3c3836ff
selection-text=ebdbb2ff
border=928374ff

[border]
width=2
radius=0
