#!/usr/bin/env bash
# Lazy agent launchers (spec section 9.1).
#
# THE IDEA
#
# Agent CLIs are npm packages that update weekly and weigh tens of megabytes
# each. Installing four of them at install time would add minutes to every
# install and be stale by the time anyone logged in. Instead each one gets a
# stub: a few hundred bytes of bash that hands the job to mise, which resolves
# and caches the real package the first time the stub is invoked.
#
# So shipping a dozen agents costs nothing, and a user who never runs `crush`
# never downloads it.
#
# WHY mise exec RATHER THAN SHELL ACTIVATION
#
# `mise activate` needs shell integration in the user's own rc file, which is
# theirs and which Archwright does not edit. `mise exec` needs nothing: the
# stub works from a script, a keybind, a cron job and a login shell alike.

# Generate the text of one stub. Pure - no I/O, no mise, no network - so the
# quoting can be tested without any of them present.
aw_agent_stub_text() {
  local name="$1" spec="$2" bin="$3"
  cat <<EOF
#!/usr/bin/env bash
# Generated by Archwright: lazy launcher for $name.
#
# Nothing was downloaded when this file was written. mise resolves and caches
#
#     $spec
#
# the first time you run this, so that first run needs a network connection.
# Every run after it is local.
#
# This file is yours: Archwright seeds it once and never overwrites it, so your
# edits survive an update, and deleting it is how you opt out of $name.
exec mise exec "$spec" -- $bin "\$@"
EOF
}

# --- validation --------------------------------------------------------------
#
# Every one of these fields is interpolated into a script that later runs as the
# user, so each is a security boundary rather than a tidiness check.
#
# `[[ =~ ]]` rather than `grep -qxE`: grep -x anchors each LINE, so a value
# containing a newline passes if any one of its lines matches. Bash's ^ and $
# anchor the whole string.

# A command name. Becomes a filename, so it must not contain a path separator.
aw_agent_valid_name() { [[ ${1-} =~ ^[a-z][a-z0-9-]*$ ]]; }

# A mise spec: an optional backend, a package that may be scoped, and an
# optional version pin - node@22, npm:typescript@5.4.5,
# npm:@openai/codex@0.20.0, go:github.com/owner/tool@latest.
#
# Anything outside this set could end the quoted string it is interpolated
# into. The backslash matters as much as the quote does: it survives the
# generator's heredoc and is then re-read as an escape inside the generated
# string, producing a stub that is not valid bash while reporting success.
#
# Kept character-for-character identical to is_mise_spec in bin/archwright.
# The two are separate because the CLI ships standalone onto the installed
# system and cannot source lib/.
aw_agent_valid_spec() {
  [[ ${1-} =~ ^([a-z][a-z0-9]*:)?@?[A-Za-z0-9._/-]+(@[A-Za-z0-9._-]+)?$ ]] || return 1
  case "$1" in */../*|../*|*/..) return 1 ;; esac
  return 0
}

# The executable inside the package. This one is interpolated UNQUOTED - it is
# a command word, not an argument - so it is the most dangerous field of the
# three and gets the strictest treatment.
aw_agent_valid_bin() { [[ ${1-} =~ ^[A-Za-z0-9][A-Za-z0-9._-]*$ ]]; }

# Regenerate the whole stub tree from a manifest.
#
# This owns its destination directory (/usr/share/archwright/agent-stubs) and
# rewrites it on every run. It is never pointed at the user's ~/.local/bin -
# the phase seeds from here into there, so a user's own edits are never
# overwritten.
aw_agent_write_stubs() {
  local manifest="$1" dest="$2" name spec bin
  [ -f "$manifest" ] || aw_die "agent manifest not found: $manifest"
  install -d -m 0755 "$dest" || aw_die "could not create $dest"

  # This directory is ours and mirrors the manifest exactly, so a row deleted
  # from the manifest stops existing here on the next run.
  #
  # To be clear about what this does NOT do: the launcher a user actually runs
  # is the seeded copy in ~/.local/bin, which is theirs and is deliberately
  # left alone. Removing a row does not uninstall anything from an existing
  # machine - it only stops new installs getting it, and stops this tree
  # disagreeing with the manifest that generated it.
  find "$dest" -mindepth 1 -maxdepth 1 -type f -exec rm -f {} + \
    || aw_die "could not clear the stub tree at $dest"

  while IFS=$'\t' read -r name spec bin; do
    [ -n "$name" ] || continue
    aw_agent_valid_name "$name" || aw_die "invalid agent name in $manifest: [$name]"
    aw_agent_valid_spec "$spec" || aw_die "invalid mise spec for $name: [$spec]"
    aw_agent_valid_bin  "$bin"  || aw_die "invalid executable name for $name: [$bin]"
    aw_agent_stub_text "$name" "$spec" "$bin" > "$dest/$name" \
      || aw_die "could not write the stub for $name"
    chmod 0755 "$dest/$name" || aw_die "could not make $name executable"
  done < <(aw_manifest_agents "$manifest")
}
