#!/usr/bin/env bash
# Lazy agent launchers (spec section 9.1).
#
# THE IDEA
#
# Agent CLIs are npm packages that update weekly and weigh tens of megabytes
# each. Installing four of them at install time would add minutes to every
# install and be stale by the time anyone logged in. Instead each one gets a
# stub: a few hundred bytes of bash that hands the job to mise, which resolves
# and caches the real package the first time the stub is invoked.
#
# So shipping a dozen agents costs nothing, and a user who never runs `crush`
# never downloads it.
#
# WHY mise exec RATHER THAN SHELL ACTIVATION
#
# `mise activate` needs shell integration in the user's own rc file, which is
# theirs and which Archwright does not edit. `mise exec` needs nothing: the
# stub works from a script, a keybind, a cron job and a login shell alike.

# Generate the text of one stub. Pure - no I/O, no mise, no network - so the
# quoting can be tested without any of them present.
aw_agent_stub_text() {
  local name="$1" spec="$2" bin="$3"
  cat <<EOF
#!/usr/bin/env bash
# Generated by Archwright: lazy launcher for $name.
#
# Nothing was downloaded when this file was written. mise resolves and caches
#
#     $spec
#
# the first time you run this, so that first run needs a network connection.
# Every run after it is local.
#
# This file is yours: Archwright seeds it once and never overwrites it, so your
# edits survive an update, and deleting it is how you opt out of $name.
exec mise exec "$spec" -- $bin "\$@"
EOF
}

# Regenerate the whole stub tree from a manifest.
#
# This owns its destination directory (/usr/share/archwright/agent-stubs) and
# rewrites it on every run. It is never pointed at the user's ~/.local/bin -
# the phase seeds from here into there, so a user's own edits are never
# overwritten.
aw_agent_write_stubs() {
  local manifest="$1" dest="$2" name spec bin
  [ -f "$manifest" ] || aw_die "agent manifest not found: $manifest"
  install -d -m 0755 "$dest" || aw_die "could not create $dest"

  while IFS=$'\t' read -r name spec bin; do
    [ -n "$name" ] || continue
    # A name is used as a filename. Anything but a plain command name could
    # write outside $dest, so this is a security check, not tidiness.
    printf '%s' "$name" | grep -qxE '[a-z][a-z0-9-]*' \
      || aw_die "invalid agent name in $manifest: [$name]"
    # The spec is interpolated into the generated script. Whitespace there
    # would split into extra arguments to mise; a quote would end the string.
    case "$spec" in
      ''|*[[:space:]]*|*'"'*|*'$'*|*'`'*)
        aw_die "invalid mise spec for $name: [$spec]" ;;
    esac
    case "$bin" in
      ''|*[[:space:]]*) aw_die "invalid executable name for $name: [$bin]" ;;
    esac
    aw_agent_stub_text "$name" "$spec" "$bin" > "$dest/$name" \
      || aw_die "could not write the stub for $name"
    chmod 0755 "$dest/$name" || aw_die "could not make $name executable"
  done < <(aw_manifest_agents "$manifest")
}
